name: ecommerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  camera: ^0.10.5+2 
  google_mlkit_face_detection: ^0.9.0
  image_picker: ^0.8.4+4
  provider: ^6.0.5
  path_provider: ^2.1.2
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/swetha.jpg
    - lib/assets/jai.jpg
    - lib/assets/Gangesh.jpeg
    - lib/assets/yuvan.jpeg


